[package]
name = "zotero-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Command-line interface for the Zotero domain library"
readme = "../../README.md"
repository.workspace = true
license.workspace = true
keywords = ["cli", "zotero"]
categories = ["command-line-utilities"]

[dependencies]
zotero-api.workspace = true

[lints]
workspace = true
